#!/bin/bash

set -xe

my_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
hostname=$(hostname)

export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@domain.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@domain.com

# Some clean up before
[ -d /tmp/workdir ] && rm -Rf /tmp/workdir
[ -d /tmp/repo ] && rm -Rf /tmp/repo
sudo yum remove -y p1

git init /tmp/repo
cat > /tmp/repo/p1.spec << EOF
Summary: A nice project p1 to test
Name: p1
Version: 1.0
Release: 1
License: GPL
Source: http://$hostname/p1-1.0.tgz
Packager: John Doe <john@doe.com>

%description
What did you expect ?

%prep
%setup -q -n p1

%install
mkdir -p %{buildroot}/srv/p1
cp run_tests.sh %{buildroot}/srv/p1

%files
%attr(0755,root,root) /srv/p1
EOF
cd /tmp/repo/
git add p1.spec && git commit -m"Packing of p1"

cd $my_path
sudo cp tests-data/*.tgz /var/www/html/

home=$HOME
[ ! -d $home/.koji ] && mkdir $home/.koji
for f in clientca.crt client.crt serverca.crt; do
    sudo cp /home/kojiadmin/.koji/$f $home/.koji/
done
sudo chown $USER:$USER $home/.koji/*

DEBUG=1 WORKSPACE=/tmp/workdir ZUUL_CHANGES=repo REPOS_CLONE_URL=file:///tmp \
    /var/lib/koji-jobs/pkg-validate.sh dist-centos7

# List local temp rpm repo
find /tmp/workdir/build_env///x86_64/
# Install the autogenerated repo file
sudo rpm -i --force /home/jenkins/rpmbuild/RPMS/noarch/build-temp-release-1.0-1.noarch.rpm
# Need to be fixed later to still use https (curl complains atm)
sudo sed -i 's/baseurl=https/baseurl=http/' /etc/yum.repos.d/build-temp-release.repo
sudo yum install -y p1
